### ISSUE TITLE
Generar tablero

### ISSUE THREAD

**Issue by Noel-S** [Usiel-03A7/chees#1]
Al generar el tablero considerar lo siguiente:

- [x] 1. Al acceder a la pagina se seleccionaran las piezas blancas por defecto.

- [x] 2. Orientacion del tablero, indicar las coordenadas del tablero 

- [x] 3. Sistema de coordenadas A-H, 1-8 para las casillas del tablero

- [x] 4. Rotacion del tablero (generar el tablero de la forma inversa como si se tuviera la perspectiva del jugador con las piezas negras)

- [x] 5. Posicion de las piezas blancas y negras al iniciar

**Comment by Usiel-03A7** [comment]
Practicaré más el pase de parámetros, funciones, clases, nombramiento de variables, manejo del dom
